### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by vyacheslavbevz99** [vyacheslavbevz99/homepage#7]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by bevz2** [comment]
https://www.fb.com/DonaldTrump
realDonaldTrump@whitehouse.gov
https://twitter.com/realDonaldTrump
https://www.instagram.com/realDonaldTrump/

**Comment by vyacheslavbevz99** [comment]
Thank you!
